In [1]:
import pandas as pd

In [29]:
def rename_columns(df, is_long=False):
    rename_map = {
        "TACOLookupSize": "taco_size",
        "TACOLookUpTime": "taco_time",
        "TACOPostProcessedLookupSize": "taco_post_size",
        "TACOPostProcessedLookupTime": "taco_post_time",
        "NoCompLookupSize": "nocomp_size",
        "NoCompLookUpTime": "nocomp_time",
        "NoCompPostProcessedLookupSize": "nocomp_post_size",
        "NoCompPostProcessedLookupTime": "nocomp_post_time",
    }
    
    if is_long:
        for key in rename_map:
            rename_map[key] = "long_" + rename_map[key]
    else:
        for key in rename_map:
            rename_map[key] = "max_" + rename_map[key]
    
    return df.rename(columns=rename_map)

In [30]:
df_taco_max = rename_columns(pd.read_csv("./enron_max_taco.csv"), False)
df_taco_long = rename_columns(pd.read_csv("./enron_long_taco.csv"), True)
df_nocomp_max = rename_columns(pd.read_csv("./enron_max_nocomp.csv"), False)
df_nocomp_long = rename_columns(pd.read_csv("./enron_long_nocomp.csv"), True)

In [31]:
df_max = pd.merge(df_taco_max, df_nocomp_max, how="left", on=["fileName", "Max Dep Ref"])
df_long = pd.merge(df_taco_long, df_nocomp_long, how="left", on=["fileName", "Longest Dep Ref"])

In [34]:
len(df_max), len(df_long)

(7382, 7381)

In [35]:
df_merged = pd.merge(df_max, df_long, how="right", on=["fileName"])

In [36]:
# df_merged.to_csv("./enron_result_merged.csv", index=False)

,fileName,Max Dep Ref,max_taco_size,max_taco_time,max_taco_post_size,max_taco_post_time,max_nocomp_size,max_nocomp_time,max_nocomp_post_size,max_nocomp_post_time,Longest Dep Ref,long_taco_size,long_taco_time,long_taco_post_size,long_taco_post_time,long_nocomp_size,long_nocomp_time,long_nocomp_post_size,long_nocomp_post_time
0,chris_germany_000_1_1_1.pst.173.xls,Sheet1:U231,1.0,9.0,1.0,10.0,1.0,30.0,1.0,31.0,Sheet1:T553,1,10,1,11,1,28,1,29
1,hunter_shively_000_1_1.pst.213.xls,Sheet1:R27,1.0,1.0,1.0,1.0,11.0,1.0,1.0,1.0,Sheet1:R27,1,0,1,0,11,1,1,2
2,phillip_allen_000_1_1.pst.220.xls,weekly:I37,10.0,1.0,7.0,1.0,10.0,1.0,7.0,1.0,weekly:F6,10,1,9,1,10,1,9,1
3,sara_shackleton_000_1_1_1.pst.40.xls,Momma Credit Form :I29,3.0,0.0,3.0,0.0,3.0,0.0,3.0,0.0,Momma Credit Form :H33,3,0,3,0,3,0,3,0
4,lindy_donoho_000_1_1_1.pst.122.xls,2001:E1,27.0,1.0,26.0,1.0,27.0,3.0,26.0,3.0,2001:J1,25,2,25,2,25,3,25,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7376,theresa_staab_000_1_1.pst.9.xls,Box Draw:E12,16.0,0.0,14.0,0.0,230.0,3.0,199.0,3.0,South Kitty:A26,1,0,1,0,29,0,1,0
7377,chris_germany_000_1_2.pst.195.xls,Sheet1:B8,63.0,0.0,7.0,0.0,63.0,1.0,7.0,1.0,Sheet1:B9,62,0,7,0,63,1,7,1
7378,dutch_quigley_000_1_1.pst.129.xls,NG-EXOTICS:K7663,2.0,0.0,2.0,0.0,2.0,0.0,2.0,0.0,NG-EXOTICS:K40,2,0,2,0,2,0,2,0
7379,don_baughman_000_1_1.pst.127.xls,Sheet1:C47,37.0,0.0,17.0,1.0,37.0,1.0,17.0,1.0,Sheet1:C38,37,0,17,0,37,1,17,1
7380,rick_buy_000_1_1_1_1.pst.40.xls,Jun01:D53,4.0,0.0,4.0,0.0,4.0,0.0,4.0,0.0,Jun01:D44,4,0,4,0,4,0,4,0